# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180402_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
